---
abstract: 'Text::Xslate View Class'
author:
  - 'Copyright (c) 2010 Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Xslate
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.8
  Scalar::Util: 0
  Text::Xslate: 0.1045
resources:
  license: http://dev.perl.org/licenses/
version: 0.00013
